const types = {
    TEXT: "TEXT",
    POSITION_GOALS: "POSITION_GOALS",
    CAMPAIGNS: "CAMPAIGNS",
    ACTIVATIONS: "ACTIVATIONS AND TACTICS",
    WORK_GOALS: "WORK_GOALS",
    WORK_SKILLS: "WORK_SKILLS",
    LIFE_EXPERIENCES: "LIFE_EXPERIENCES",
    CULTURE_GROUPS: "CULTURE_GROUPS",
    BRAND_AUDIT: "BRAND_AUDIT",
    POSSES_CARDS: "POSSES_CARDS"
}

export default types